[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = [
  "npm run build:types",
  "npx prisma generate",
  "npm run build:web"
]

[start]
cmd = "npx prisma migrate deploy && npm run start"
